[providers]
python = "3.11"
nodejs = "18"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install",
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
